/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cesarypong;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Interface extends javax.swing.JFrame {
    
    Cesar x = new Cesar();
    ZigZag y = new ZigZag();
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        x.setPrivatekey(Integer.parseInt(txt_privatekey1.getText()));
        y.setPrivatekey(Integer.parseInt(txt_privatekey2.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_encrypt = new javax.swing.JButton();
        btn_decrypt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_privatekey1 = new javax.swing.JTextField();
        txt_privatekey2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_encryptm = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_decryptm = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Descrypted Message");

        btn_encrypt.setText("Encrypt");
        btn_encrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_encryptMouseClicked(evt);
            }
        });

        btn_decrypt.setText("Decrypt");
        btn_decrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_decryptMouseClicked(evt);
            }
        });

        jLabel3.setText("Encrypted Message");

        txt_privatekey1.setText("0");

        txt_privatekey2.setText("1");

        jLabel4.setText("Private Key 1");

        jLabel5.setText("Private Key 2");

        txt_encryptm.setColumns(20);
        txt_encryptm.setLineWrap(true);
        txt_encryptm.setRows(5);
        txt_encryptm.setWrapStyleWord(true);
        txt_encryptm.setAutoscrolls(false);
        jScrollPane1.setViewportView(txt_encryptm);

        txt_decryptm.setColumns(20);
        txt_decryptm.setLineWrap(true);
        txt_decryptm.setRows(5);
        txt_decryptm.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_decryptm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_privatekey1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_privatekey2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_encrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_decrypt, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addGap(0, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_privatekey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_privatekey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btn_decrypt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_encrypt)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_encryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_encryptMouseClicked
        x.setPrivatekey(Integer.parseInt(txt_privatekey1.getText()));
        y.setPrivatekey(Integer.parseInt(txt_privatekey2.getText()));
        if(y.getPrivatekey() >= 1){
            x.setPrivatekey(Integer.parseInt(txt_privatekey1.getText()));
            y.setPrivatekey(Integer.parseInt(txt_privatekey2.getText()));
            String text = x.encrypt(txt_encryptm.getText());
            //JOptionPane.showMessageDialog(rootPane, x.getPrivatekey());
            txt_decryptm.setText(y.encrypt(text));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Private key 2 must be greater than or equal to 1");
        }
    }//GEN-LAST:event_btn_encryptMouseClicked

    private void btn_decryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_decryptMouseClicked
        x.setPrivatekey(Integer.parseInt(txt_privatekey1.getText()));
        y.setPrivatekey(Integer.parseInt(txt_privatekey2.getText()));
        if(y.getPrivatekey() >= 1){
            x.setPrivatekey(Integer.parseInt(txt_privatekey1.getText()));
            y.setPrivatekey(Integer.parseInt(txt_privatekey2.getText()));
            String text = y.decrypt(txt_decryptm.getText());
            txt_encryptm.setText(x.decrypt(text));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Private key 2 must be greater than or equal to 1");
        }
    }//GEN-LAST:event_btn_decryptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_decryptm;
    private javax.swing.JTextArea txt_encryptm;
    private javax.swing.JTextField txt_privatekey1;
    private javax.swing.JTextField txt_privatekey2;
    // End of variables declaration//GEN-END:variables
}
